# Generated by Django 4.2.5 on 2023-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procuradorexit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurador",
            name="casos_ganados",
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name="procurador",
            name="numero_colegiado",
            field=models.IntegerField(max_length=5),
        ),
    ]
