# Generated by Django 4.2.5 on 2023-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procuradorexit", "0002_alter_procurador_casos_ganados_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurador",
            name="casos_ganados",
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="procurador",
            name="numero_colegiado",
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
